In [3]:
import numpy as np

#Confusion Matrix

In [ ]:
def confusion_matrix(true,pred):
  classes = set(true + pred)
  num_classes = len(classes)
  shape = (num_classes, num_classes)
  mat = np.zeros(shape)
  n = max(len(true),len(pred))
  for i in range(num_classes):
    for j in range(num_classes):
      for k in range(n):
        if true[k]-1 == i:
          if pred[k]-1 == j:
            mat[i][j] = mat[i][j] + 1
  return mat

In [ ]:
actual = [1,1,2,3,4,1,5,1,6]
predicted = [1,2,2,3,4,6,5,1,2]
confusion_matrix(actual, predicted)

array([[2., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.]])

#Matrix Multiplication

In [ ]:
def mul(x,y):
  lst = []
  for i in range(len(x)):
    lst.append(x[i]*y[i])
  return sum(lst)

In [ ]:
def mat_mul(x,y):
  if x.shape[1] != y.shape[0]:
    return - 1
  res = np.zeros((x.shape[0],y.shape[1]))
  for i in range(res.shape[0]):
    for j in range(res.shape[1]):
      res[i][j] = mul(x[i],y[:,j])
  return res

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8],[9,10],[11,12]])
mat_mul(x,y)

array([[ 58.,  64.],
       [139., 154.]])

Implement a function to find transpose of a matrix without built-in functions

In [10]:
def transpose(mat):
  size = mat.shape
  res = np.zeros((size[1],size[0]))
  for i in range(size[0]):
    for j in range(size[1]):
      res[i][j] = mat[j][i]
  return res

In [11]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
transpose(x)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

#Convolution operation

In [ ]:
def get_target_size(image_size, kernal_size, stride):
  res_size = 0
  for i in range(0,image_size,stride):
    temp = i + kernal_size
    if temp <= image_size:
      res_size += 1
  return res_size

In [ ]:
def convolution(image, kernal, stride):
  size = get_target_size(image.shape[0],kernal.shape[0],1)
  k = kernal.shape[0]
  res = np.zeros((size,size))
  for i in range(0,size,stride[0]):
    for j in range(0,size,stride[1]):
      if i <= image.shape[0] and j<= image.shape[1]:
        res[i][j] = np.sum(mat_mul(image[i:i+k,j:j+k], kernal))
  return res

In [ ]:
image = np.random.rand(5,5)
kernal = np.random.rand(3,3)
convolution(image,kernal,(1,1))

array([[8.6253595 , 6.80400159, 5.7824317 ],
       [7.51309514, 7.90982945, 7.70477709],
       [8.14378264, 8.34831147, 7.33213631]])

#Max Pooling

In [ ]:
def max_pooling(image, pool_size, stride):
  shape = image.shape
  size = get_target_size(image.shape[0],pool_size,stride)
  res = np.zeros((size,size))
  k = pool_size
  for i in range(0,size,stride):
    for j in range(0,size,stride):
      if i <= image.shape[0] and j<= image.shape[1]:
        res[i][j] = np.max(image[i:i+k,j:j+k])
  return res

In [ ]:
max_pooling(image,3,1)

array([[0.94922753, 0.94741825, 0.80064993],
       [0.94922753, 0.94741825, 0.85659342],
       [0.94922753, 0.94741825, 0.86046624]])

#Average Pooling

In [ ]:
def avg_pooling(image, pool_size, stride):
  shape = image.shape
  size = get_target_size(image.shape[0],pool_size,stride)
  res = np.zeros((size,size))
  k = pool_size
  for i in range(0,size,stride):
    for j in range(0,size,stride):
      if i <= image.shape[0] and j<= image.shape[1]:
        res[i][j] = np.average(image[i:i+k,j:j+k])
  return res

In [ ]:
avg_pooling(image,3,1)

array([[0.59457884, 0.52056127, 0.43459679],
       [0.54649805, 0.56851579, 0.60155789],
       [0.59969047, 0.58600709, 0.57230721]])

#Gradient Descent

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3,4,5, 6,7,8,9,10])
x[-1]

10